### ISSUE TITLE
Error lifecycle hook

### ISSUE THREAD

**Issue by DaveLo** [evilkiwi/lamware#2]
**Is your feature request related to a problem? Please describe.**
The issue I'm having relates to doing cleanup in cases of thrown errors in a handler. I might need to ensure that a rollback event gets sent out to the event stream, or that a db connection gets closed.

**Describe the solution you'd like**
An onError or catch hook in the lifecycle of middleware to perform cleanup.

**Describe alternatives you've considered**
This code could go into the event handler itself, but since the middleware is abstracting away setup it makes sense to also contain cleanup for both after and error lifecycles.

**Additional context**
I've just started using this library and am liking it in general, just ran into this issue while converting some of my existing wrapper functions to middleware

**Comment by oyed** [comment]
Makes sense to me - are you wanting the hook to run on any uncaught error in the handler and the other hooks? Just want to make sure I understand completely 😁

**Comment by devlsh** [comment]
I'll add this in a few hours - my initial thoughts (post-coffee) are:

1. Middleware can provide an `error` hook which is given context and the error that caused it
2. When it catches an error, Lamware will execute any `error` hooks **in parallel**, ignoring any further steps after that
    - i.e. if the error occurs in a `before` hook, the handler & `after` hooks will never be executed
3. It will wrap `before`, `after`, `init` and the handler itself for catching uncaught errors (It will pass which method caused the error, as well as the middleware name that caused it (if it was during `before` or `after`) to the `error` handler

And I'm glad you're enjoying the library! :)

**Comment by devlsh** [comment]
I've released `@lamware/core@1.3.0` with `uncaughtException` support. The only difference with my previous comment is the lack of `init` support for catching uncaught exceptions. It's a difficult one, since an uncaught exception during `init` is a critical issue, and only Middleware registered up to the one that throws the error is registered.

Regardless, let me know if you need anything else.
https://docs.oyed.dev/lamware/middleware.html#handling-errors
